**1. Write a function so that the columns of the output matrix are powers of the input
vector.**

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [7]:
import numpy as np

def Vandermonde(x, N, increasing = False):
    if increasing:
        print(np.array([ j** i for j in x for i in range(N)]).reshape(len(x), N))
    else:
        print(np.array([ j** (N-1-i) for j in x for i in range(N)]).reshape(len(x), N))
        
iterables = [5,6,7,8,9]

N = 5

print('when  INCREASING ')

Vandermonde(np.array(iterables),N, increasing= True)


print('when DECREASING ')

Vandermonde(np.array(iterables),N, increasing = False)



when  INCREASING 
[[   1    5   25  125  625]
 [   1    6   36  216 1296]
 [   1    7   49  343 2401]
 [   1    8   64  512 4096]
 [   1    9   81  729 6561]]
when DECREASING 
[[ 625  125   25    5    1]
 [1296  216   36    6    1]
 [2401  343   49    7    1]
 [4096  512   64    8    1]
 [6561  729   81    9    1]]


**2. Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [ ]:
#dont run the below cell, its an hint

**Problem Statement 2:**
    
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [26]:
def moving_avg(x,k):
    m=1
    ma_output=np.convolve(x, np.ones(k),'valid')/k
    for i in ma_output:
        print ("y{0}={1:.2f}".format(m,i))
        m=m+1
    

In [27]:
x=np.array([1,4,5,7,8,9,6,3,1,4,8,5,23,69])
k=3
moving_avg(x,k)

y1=3.33
y2=5.33
y3=6.67
y4=8.00
y5=7.67
y6=6.00
y7=3.33
y8=2.67
y9=4.33
y10=5.67
y11=12.00
y12=32.33


__this is how convolve works__

[1,1,1,1]
[5,3,8,10,2,1,5,1,0,2]
= (1*5 + 1*3 + 1*8 + 1*10) / w = 6.5

[1,1,1,1]
[5,3,8,10,2,1,5,1,0,2]
= (1*3 + 1*8 + 1*10 + 1*2) / w = 5.75